name = "ashlynn-bot"
main = "worker/worker.js" 
type = "javascript"
account_id = "16d446ea4c59f5b64edd1648d778144b"
workers_dev = true
compatibility_date = "2024-02-10"

[vars]
BOT_TOKEN = "7650889353:AAHaCrrj_s-CT9W-czSPQ4McRnGxh31h4TA"

# Define the D1 database
[[d1_databases]]
binding = "chat"
database_name = "userdata"
database_id = "888a64fd-2f67-4082-8963-ac83c5015732"
