name = "ashlynn-bot"
main = "worker/worker.js" 
type = "javascript"
account_id = "16d446ea4c59f5b64edd1648d778144b"
workers_dev = true
compatibility_date = "2024-02-10"

[vars]
BOT_TOKEN = "7583224858:AAGhuOlKKMCEWypUI0dtiMo589q3La9ngDI"

# Define the D1 database
[[d1_databases]]
binding = "chat"
database_name = "ashlynn_repo"
database_id = "your-database-id"
